=== CHIRDL-Openmrs-Modules/chicaops/api/src/test/resources/dbunitFiles/tableSetupDTD.dtd
<!ELEMENT dataset (
    person*,
    role*,
    users*,
    location*,
    patient*,
    global_property*,
    dss_rule*,
    dss_rule_type*,
    dss_rule_entry*,
    form*,
    field*,
    encounter_type*,
    encounter*,
    atd_patient_atd_element*)>

<!ELEMENT atd_patient_atd_element EMPTY>
<!ATTLIST atd_patient_atd_element
    atd_id CDATA #REQUIRED
    patient_id CDATA #REQUIRED
    form_id CDATA #REQUIRED
    field_id CDATA #REQUIRED
    text CDATA #IMPLIED
    rule_id CDATA #REQUIRED
    form_instance_id CDATA #REQUIRED
    creation_time CDATA #REQUIRED
    encounter_id CDATA #IMPLIED
    location_id CDATA #REQUIRED
>

<!ELEMENT dss_rule EMPTY>
<!ATTLIST dss_rule
    rule_id CDATA #REQUIRED
    class_filename CDATA #REQUIRED
    creation_time CDATA #REQUIRED
    title CDATA #IMPLIED
    version CDATA #IMPLIED
    institution CDATA #IMPLIED
    author CDATA #IMPLIED
    specialist CDATA #IMPLIED
    ruleCreationDate CDATA #IMPLIED
    purpose CDATA #IMPLIED
    explanation CDATA #IMPLIED
    keywords CDATA #IMPLIED
    citations CDATA #IMPLIED
    links CDATA #IMPLIED
    data CDATA #IMPLIED
    logic CDATA #IMPLIED
    action CDATA #IMPLIED
    last_modified CDATA #IMPLIED
    token_name CDATA #IMPLIED
    age_min_units CDATA #IMPLIED
    age_max_units CDATA #IMPLIED
    age_min CDATA #IMPLIED
    age_max CDATA #IMPLIED
>

<!ELEMENT dss_rule_entry EMPTY>
<!ATTLIST dss_rule_entry
    rule_entry_id CDATA #REQUIRED
    rule_type_id CDATA #REQUIRED
    rule_id CDATA #REQUIRED
    priority CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT dss_rule_type EMPTY>
<!ATTLIST dss_rule_type
    rule_type_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT encounter EMPTY>
<!ATTLIST encounter
    encounter_id CDATA #REQUIRED
    encounter_type CDATA #IMPLIED
    patient_id CDATA #REQUIRED
    location_id CDATA #REQUIRED
    form_id CDATA #IMPLIED
    encounter_datetime CDATA #REQUIRED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    voided CDATA #REQUIRED
    voided_by CDATA #IMPLIED
    date_voided CDATA #IMPLIED
    void_reason CDATA #IMPLIED
    scheduled_datetime CDATA #IMPLIED
    insurance_sms_code CDATA #IMPLIED
    printer_location CDATA #IMPLIED
    insurance_carrier_code CDATA #IMPLIED
    insurance_plan_code CDATA #IMPLIED
    uuid CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    data_changed CDATA #IMPLIED
    visit_id CDATA #IMPLIED
>

<!ELEMENT encounter_type EMPTY>
<!ATTLIST encounter_type
    encounter_type_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT form EMPTY>
<!ATTLIST form
    form_id CDATA #REQUIRED
    name CDATA #REQUIRED
    version CDATA #REQUIRED
    build CDATA #IMPLIED
    published CDATA #REQUIRED
    description CDATA #IMPLIED
    encounter_type CDATA #IMPLIED
    template CDATA #IMPLIED
    xslt CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retired_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT field EMPTY>
<!ATTLIST field
    field_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    field_type CDATA #IMPLIED
    concept_id CDATA #IMPLIED
    table_name CDATA #IMPLIED
    attribute_name CDATA #IMPLIED
    default_value CDATA #IMPLIED
    select_multiple CDATA #REQUIRED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT global_property EMPTY>
<!ATTLIST global_property
    property CDATA #REQUIRED
    property_value CDATA #IMPLIED
    description CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT location EMPTY>
<!ATTLIST location
    location_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    address1 CDATA #IMPLIED
    address2 CDATA #IMPLIED
    city_village CDATA #IMPLIED
    state_province CDATA #IMPLIED
    postal_code CDATA #IMPLIED
    country CDATA #IMPLIED
    latitude CDATA #IMPLIED
    longitude CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    county_district CDATA #IMPLIED
    address3 CDATA #IMPLIED
    address6 CDATA #IMPLIED
    address5 CDATA #IMPLIED
    address4 CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    parent_location CDATA #IMPLIED
    uuid CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    data_changed CDATA #IMPLIED
    address7 CDATA #IMPLIED
    address8 CDATA #IMPLIED
    address9 CDATA #IMPLIED
    address10 CDATA #IMPLIED
    address11 CDATA #IMPLIED
    address12 CDATA #IMPLIED
    address13 CDATA #IMPLIED
    address14 CDATA #IMPLIED
    address15 CDATA #IMPLIED
>

<!ELEMENT patient EMPTY>
<!ATTLIST patient
    patient_id CDATA #REQUIRED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    voided CDATA #REQUIRED
    voided_by CDATA #IMPLIED
    date_voided CDATA #IMPLIED
    void_reason CDATA #IMPLIED
    allergy_status CDATA #REQUIRED
>

<!ELEMENT person EMPTY>
<!ATTLIST person
    person_id CDATA #REQUIRED
    gender CDATA #IMPLIED
    birthdate CDATA #IMPLIED
    birthdate_estimated CDATA #IMPLIED
    dead CDATA #REQUIRED
    death_date CDATA #IMPLIED
    cause_of_death CDATA #IMPLIED
    creator CDATA #IMPLIED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    voided CDATA #REQUIRED
    voided_by CDATA #IMPLIED
    date_voided CDATA #IMPLIED
    void_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
    deathdate_estimated CDATA #IMPLIED
    birthtime CDATA #IMPLIED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
    role CDATA #REQUIRED
    description CDATA #REQUIRED
    uuid CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #REQUIRED
    system_id CDATA #REQUIRED
    username CDATA #IMPLIED
    password CDATA #IMPLIED
    salt CDATA #IMPLIED
    secret_question CDATA #IMPLIED
    secret_answer CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    person_id CDATA #REQUIRED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

=== CHIRDL-Openmrs-Modules/chicaops/api/src/test/resources/dbunitFiles/tableSetup.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "tableSetupDTD.dtd">
<dataset>
    <person person_id="1" gender="" birthdate="1975-06-30" birthdate_estimated="false" dead="false" date_created="2005-01-01 00:00:00.0" voided="false" uuid="6adb7c42-cfd2-4301-b53b-ff17c5654ff7"/>
    <person person_id="2" gender="" birthdate="1975-06-30" birthdate_estimated="false" dead="false" date_created="2005-01-01 00:00:00.0" voided="false" uuid="6adb7c42-cfd2-4301-b53b-ff17c5654ff8"/>
    <role role="Anonymous" description="Everyone and their brother should have this role" uuid="5b773b4d-90be-4d3f-81ca-cbb1441541ec"/>
    <role role="Authenticated" description="Every person logged in automatically has this role." uuid="0dc8933e-7105-4c3b-b86c-15618d854660"/>
    <role role="System Developer" description="Administrators of the OpenMRS .. have additional access to change fundamental structure of the database model." uuid="0e43640b-67d1-4458-b47f-b64fd8ce4b0d"/>
    <users user_id="1" person_id="1" system_id="1-8" username="admin" password="4a1750c8607d0fa237de36c6305715c223415189" salt="c788c6ad82a157b712392ca695dfcf2eed193d7f" secret_question="" creator="1" date_created="2005-01-01 00:00:00.0" changed_by="1" date_changed="2007-09-20 21:54:12.0" retired="false" retire_reason="" uuid="1010d442-e134-11de-babe-001e378eb67e"/>
    <location location_id="2987772" name="location_2987772" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000001"/>
    <patient patient_id="1" creator="1" date_created="2017-07-19 11:34:46" voided="0" allergy_status="Unknown"/>
    <patient patient_id="2" creator="1" date_created="2017-07-19 11:34:46" voided="0" allergy_status="Unknown"/>
    <global_property property="chicaops.dashboardConfigFile" property_value="src/test/resources/DashboardConfig.xml" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000002"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/MDEPFUPWS.class" rule_id="3" creation_time="2009-01-07 13:17:52" title="Depression Maternal Depression PWS Followup" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Prompts MD to follow up suspected maternal depression. Checks if parent has gotten mental health treatment or is no longer depressed." explanation="This prompt is fired if MD concluded on PWS parent may have depression." keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="MDEPFUPWS" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule1.class" rule_id="4" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 1" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule1" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule2.class" rule_id="5" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 2" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule2" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule3.class" rule_id="6" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 3" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule3" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule4.class" rule_id="7" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 4" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule4" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule5.class" rule_id="8" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 5" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule5" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule_type rule_type_id="1" name="PWS" creator="1" date_created="2017-07-19 11:32:21" retired="0" uuid="7cb211ff-6c97-11e7-9be2-0a0027000003"/>
    <dss_rule_type rule_type_id="2" name="PWS_2" creator="1" date_created="2017-08-20 11:32:21" retired="0" uuid="7cb211ff-6c97-11e7-9be2-0a0027000004"/>
    <dss_rule_entry rule_entry_id="1" rule_type_id="1" rule_id="3" priority="227" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000006"/>
    <dss_rule_entry rule_entry_id="2" rule_type_id="1" rule_id="4" priority="222" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000007"/>
    <dss_rule_entry rule_entry_id="3" rule_type_id="1" rule_id="5" priority="220" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000008"/>
    <dss_rule_entry rule_entry_id="4" rule_type_id="2" rule_id="3" priority="227" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000009"/>
    <dss_rule_entry rule_entry_id="5" rule_type_id="2" rule_id="4" priority="223" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000010"/>
    <dss_rule_entry rule_entry_id="6" rule_type_id="2" rule_id="5" priority="224" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000011"/>
    <form form_id="7629982" name="PWS" version="1.0" published="0" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000013"/>
    <form form_id="7629983" name="PWS_2" version="1.0" published="0" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000014"/>
    <field field_id="992872" name="test_field" select_multiple="0" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000015"/>
    <encounter_type encounter_type_id="23232323" name="Test" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000016"/>
